// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pargdgwfscecfioeekdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcmdkZ3dmc2NlY2Zpb2Vla2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjY3NjksImV4cCI6MjA2MzU0Mjc2OX0.z-c99zfMxRLSAILvTBLSdFUTa653VqzZRaiz1fZioyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});